<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<div class="no-print mb-3">
    <button onclick="window.print()" class="btn btn-primary"><i class="fa-solid fa-print"></i> Print</button>
    <a href="<?= base_url('payments/receipt/'.$payment['id'].'/pdf') ?>" class="btn btn-outline-danger"><i class="fa-solid fa-file-pdf"></i> Download PDF</a>
    <a href="<?= base_url('payments') ?>" class="btn btn-outline-secondary">Back</a>
</div>

<div class="receipt-box">
    <div class="text-center mb-4">
        <h4 class="mb-0">REPUBLIC OF THE PHILIPPINES</h4>
        <h5 class="mb-0">CITY GOVERNMENT OF GENERAL SANTOS</h5>
        <h5 class="fw-bold">PUBLIC MARKET — ARKALABA RESIBO</h5>
        <p class="small text-muted mb-0">WBMM Official Receipt</p>
    </div>
    <hr>
    <div class="row mb-2"><div class="col-6"><strong>Reference No:</strong></div><div class="col-6"><?= esc($payment['reference_no']) ?></div></div>
    <div class="row mb-2"><div class="col-6"><strong>Date:</strong></div><div class="col-6"><?= date('F d, Y h:i A', strtotime($payment['payment_date'])) ?></div></div>
    <div class="row mb-2"><div class="col-6"><strong>Vendor:</strong></div><div class="col-6"><?= esc($payment['vendor_name']) ?> (<?= esc($payment['vendor_no']) ?>)</div></div>
    <div class="row mb-2"><div class="col-6"><strong>Stall:</strong></div><div class="col-6"><?= esc($payment['stall_code'] ?? 'Ambulant') ?> — <?= esc($payment['section'] ?? 'N/A') ?></div></div>
    <div class="row mb-2"><div class="col-6"><strong>Type:</strong></div><div class="col-6"><?= esc(ucfirst($payment['stall_type'] ?? $payment['vendor_type'])) ?></div></div>
    <?php if (!empty($payment['sqm'])): ?>
    <div class="row mb-2"><div class="col-6"><strong>SQM:</strong></div><div class="col-6"><?= esc($payment['sqm']) ?> sqm</div></div>
    <?php endif; ?>
    <div class="row mb-2"><div class="col-6"><strong>Rate Used:</strong></div><div class="col-6">₱<?= number_format((float)$payment['rate_used'], 2) ?></div></div>
    <div class="row mb-2"><div class="col-6"><strong>Payment Type:</strong></div><div class="col-6"><?= esc(ucfirst($payment['payment_type'])) ?></div></div>
    <div class="row mb-2"><div class="col-6"><strong>Period Covered:</strong></div><div class="col-6"><?= esc($payment['period_start']) ?> to <?= esc($payment['period_end']) ?></div></div>
    <hr>
    <div class="row mb-2"><div class="col-6"><strong>Computed Amount:</strong></div><div class="col-6">₱<?= number_format((float)$payment['computed_amount'], 2) ?></div></div>
    <div class="row mb-3"><div class="col-6"><strong>Amount Paid:</strong></div><div class="col-6 fs-4 fw-bold">₱<?= number_format((float)$payment['amount_paid'], 2) ?></div></div>
    <?php if ((float)$payment['amount_paid'] < (float)$payment['computed_amount']): ?>
    <div class="alert alert-warning py-2 small">Underpayment noted. <?= esc($payment['notes'] ?? '') ?></div>
    <?php endif; ?>
    <div class="row mb-4"><div class="col-6"><strong>Collected By:</strong></div><div class="col-6"><?= esc($payment['collector_name']) ?> (Maningil)</div></div>
    <?php if ($payment['notes']): ?><p class="small"><strong>Notes:</strong> <?= esc($payment['notes']) ?></p><?php endif; ?>
    <div class="text-center mt-5 pt-4 border-top">
        <p class="small text-muted mb-0">This document is system-generated by WBMM.</p>
        <p class="small text-muted">General Santos City Public Market · LGU General Santos City</p>
    </div>
</div>
<?= $this->endSection() ?>
